# CI name
name: Rutubishi CI

# indicate conditions when the CI workflow can run
on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

# define jobs that will run within our workflow (each job will run in parallel)
jobs:
  rubo_cop_n_app_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1.1' # not necessary if you have the .ruby-version file
          bundler-cache: true
      - run: bundle exec rubocop
      - run: bundle exec rspec spec/
  